# Generated by Django 2.2.14 on 2020-08-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
