# Generated by Django 2.2.14 on 2020-08-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suppler',
            new_name='supplier',
        ),
    ]
