# Generated by Django 2.2.14 on 2020-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200808_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
